name: medi_care
description: "Project to deliver to medicine in the least amount of time."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1
  get: ^4.6.6
  iconsax: ^0.0.8
  smooth_page_indicator: ^1.1.0
  readmore: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^2.0.0





flutter:




  uses-material-design: true


  assets:
    - assets/icons/categories/
    - assets/icons/auth/
    - assets/images/banner/
    - assets/images/medicine/
    - assets/images/on_boarding_image/


























