// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvBIqL4osZFBHrUj1TcFmyd1QNNjwWY1o',
    appId: '1:260858372792:web:ca51756939c38f58ab4a4d',
    messagingSenderId: '260858372792',
    projectId: 'medi-care-36c49',
    authDomain: 'medi-care-36c49.firebaseapp.com',
    storageBucket: 'medi-care-36c49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd7k8RN8Arf-0qtS95VHWjduUH6Cu_jOU',
    appId: '1:260858372792:android:61908786c618935fab4a4d',
    messagingSenderId: '260858372792',
    projectId: 'medi-care-36c49',
    storageBucket: 'medi-care-36c49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLdsxaawsPRYFaRqPGTpTLWVSpH0P-X4g',
    appId: '1:260858372792:ios:bc4f402b5504450eab4a4d',
    messagingSenderId: '260858372792',
    projectId: 'medi-care-36c49',
    storageBucket: 'medi-care-36c49.appspot.com',
    iosBundleId: 'com.karan.medicare.mediCare',
  );
}
